
export const useTenCodes = () => {
    return [
        { code: '10-1', title_ru: 'Принимаю плохо, неуверенно', title_en: '' },
        { code: '10-2', title_ru: 'Принимаю уверенно', title_en: '' },
        { code: '10-3', title_ru: 'Прекратите передачу', title_en: '' },
        { code: '10-4', title_ru: 'Сообщение принял (ОК)', title_en: '' },
        { code: '10-5', title_ru: 'Ретранслируйте сообщение', title_en: '' },
        { code: '10-6', title_ru: 'Я занят, подождите', title_en: '' },
        { code: '10-7', title_ru: 'Связь закончил, выключаю станцию', title_en: '' },
        { code: '10-8', title_ru: 'Готов к работе, можете вызывать меня', title_en: '' },
        { code: '10-9', title_ru: 'Повторите ваше сообщение', title_en: '' },
        { code: '10-10', title_ru: 'Связь закончил, нахожусь на приеме', title_en: '' },
        { code: '10-11', title_ru: 'Говорите медленнее', title_en: '' },
        { code: '10-12', title_ru: 'Если клиенты/посетители', title_en: '' },
        { code: '10-13', title_ru: 'Сообщите погоду / дорожную обстановку', title_en: '' },
        { code: '10-14', title_ru: 'Сопровождаю объект', title_en: '' },
        { code: '10-15', title_ru: 'Следую с ...', title_en: '' },
        { code: '10-16', title_ru: 'Перехватите ... в ...', title_en: '' },
        { code: '10-17', title_ru: 'Срочное сообщение!', title_en: '' },
        { code: '10-18', title_ru: 'Есть ли информация для меня?', title_en: '' },
        { code: '10-19', title_ru: 'Для вас ничего нет / Возвращайтесь на базу', title_en: '' },
        { code: '10-20', title_ru: 'Моё местонахождение ...', title_en: '' },
        { code: '10-21', title_ru: 'Позвоните по телефону ...', title_en: '' },
        { code: '10-22', title_ru: 'Сообщите также <кому-либо>', title_en: '' },
        { code: '10-23', title_ru: 'Будьте на приеме', title_en: '' },
        { code: '10-24', title_ru: 'Последнее задание выполнено', title_en: '' },
        { code: '10-25', title_ru: 'Вы можете связаться с ...?', title_en: '' },
        { code: '10-26', title_ru: 'Последняя информация (сообщение) отменяется', title_en: '' },
        { code: '10-27', title_ru: 'Я перехожу на канал № ...', title_en: '' },
        { code: '10-28', title_ru: 'Какой ваш позывной?', title_en: '' },
        { code: '10-29', title_ru: 'Время для связи вышло', title_en: '' },
        { code: '10-30', title_ru: 'Это не разрешается правилами связи', title_en: '' },
        { code: '10-32', title_ru: 'Даю вам контроль/настройку', title_en: '' },
        { code: '10-33', title_ru: 'Имею сообщение об аварии/бедствии', title_en: '' },
        { code: '10-34', title_ru: 'Нужна помощь', title_en: '' },
        { code: '10-35', title_ru: 'Конфиденциальная информация', title_en: '' },
        { code: '10-36', title_ru: 'Точное время сейчас ...', title_en: '' },
        { code: '10-37', title_ru: 'Нужна техпомощь', title_en: '' },
        { code: '10-38', title_ru: 'Нужна "скорая помощь"', title_en: '' },
        { code: '10-39', title_ru: 'Ваше сообщение передано', title_en: '' },
        { code: '10-41', title_ru: 'Переключитесь на канал № ...', title_en: '' },
        { code: '10-55', title_ru: 'Замечен пьяный водитель', title_en: '' },
        { code: '10-58', title_ru: 'Прямое движение', title_en: '' },
        { code: '10-59', title_ru: 'Эскорт или сопровождение/Проверка безопасности', title_en: '' },
        { code: '10-60', title_ru: 'Какой номер следующего сообщения?', title_en: '' },
        { code: '10-62', title_ru: 'Не могу вас принять. Позвоните по телефону...', title_en: '' },
        { code: '10-62si', title_ru: 'Не могу вас принять. Передите на НБП (LSB)', title_en: '' },
        { code: '10-62su', title_ru: 'Не могу вас принять. Передите на ВБП (USB)', title_en: '' },
        { code: '10-63', title_ru: 'Сетью управляет ...', title_en: '' },
        { code: '10-64', title_ru: 'Сеть свободна', title_en: '' },
        { code: '10-65', title_ru: 'Жду вашего следующего сообщения/задания', title_en: '' },
        { code: '10-67', title_ru: 'Все задания выполнены', title_en: '' },
        { code: '10-68', title_ru: 'Отправка сообщения', title_en: '' },
        { code: '10-70', title_ru: 'Пожар на ...', title_en: '' },
        { code: '10-71', title_ru: 'Связывайтесь в порядке очереди', title_en: '' },
        { code: '10-73', title_ru: 'Контроль скорости на ...', title_en: '' },
        { code: '10-75', title_ru: 'Вы создаете помехи', title_en: '' },
        { code: '10-77', title_ru: 'Извините, ошибочный вызов', title_en: '' },
        { code: '10-80', title_ru: 'Идет преследование', title_en: '' },
        { code: '10-81', title_ru: 'Закажите номер в гостинице для ...', title_en: '' },
        { code: '10-83', title_ru: 'Закажите комнату для ...', title_en: '' },
        { code: '10-84', title_ru: 'Мой телефон ...', title_en: '' },
        { code: '10-85', title_ru: 'Мой адрес ...', title_en: '' },
        { code: '10-91', title_ru: 'Говорите громче', title_en: '' },
        { code: '10-92', title_ru: 'Ваш передатчик не настроен', title_en: '' },
        { code: '10-93', title_ru: 'Проверьте мою частоту в этом канале', title_en: '' },
        { code: '10-94', title_ru: 'Дайте счёт/настройку', title_en: '' },
        { code: '10-95', title_ru: 'Дайте несущую на 5 секунд', title_en: '' },
        { code: '10-99', title_ru: 'Задание выполнено, всё в порядке', title_en: '' },
        { code: '10-100', title_ru: 'Мне нужно отойти', title_en: '' },
        { code: '10-200', title_ru: 'Нужна полиция в ...', title_en: '' },
    ]
}